package com.example.mall.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.mall.model.bean.PersonInfor;
import com.example.mall.model.bean.ProductInfo;

import com.example.mall.model.dao.PersonInforDao;
import com.example.mall.model.dao.ProductInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personInforDaoConfig;
    private final DaoConfig productInfoDaoConfig;

    private final PersonInforDao personInforDao;
    private final ProductInfoDao productInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personInforDaoConfig = daoConfigMap.get(PersonInforDao.class).clone();
        personInforDaoConfig.initIdentityScope(type);

        productInfoDaoConfig = daoConfigMap.get(ProductInfoDao.class).clone();
        productInfoDaoConfig.initIdentityScope(type);

        personInforDao = new PersonInforDao(personInforDaoConfig, this);
        productInfoDao = new ProductInfoDao(productInfoDaoConfig, this);

        registerDao(PersonInfor.class, personInforDao);
        registerDao(ProductInfo.class, productInfoDao);
    }
    
    public void clear() {
        personInforDaoConfig.clearIdentityScope();
        productInfoDaoConfig.clearIdentityScope();
    }

    public PersonInforDao getPersonInforDao() {
        return personInforDao;
    }

    public ProductInfoDao getProductInfoDao() {
        return productInfoDao;
    }

}
